services:
  # A Docker web service
  - type: web
    name: AList+Aria2
    runtime: go
    repo: https://github.com/Desseer/defse.git # optional
    region: Singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    buildCommand: ./install.sh
    startCommand: ./entrypoint.sh

